version: '3.9'
services:
  postgresql:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=artifact
      - POSTGRES_PASSWORD=artifact
      - POSTGRES_DB=artifact
  pgAdmin:
    image: dpage/pgadmin4:6.1
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=artifact@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=artifact

#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - POSTGRESQL_DB_HOST=postgresql

volumes:
  db_data:
    driver: local