spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/artifact
    username: artifact
    password: artifact

flyway:
  url: jdbc:postgresql://localhost:5432/artifact
  user: artifact
  password: artifact
  enabled: true
  locations:
    - 'classpath:db/migration'
