/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 6.3.0-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";
import { htmlReport } from "https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js";


const BASE_URL = "http://localhost:8080";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.
const TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJpc3MiOiJhcnRpZmFjdCIsInVzZXJJZCI6MSwiaWF0IjoxNjczOTgwMzU0fQ.e4XggjCpWcb46Yol3OLua6WCWtZEzL1UGJ51jbcWJhk"
const INFORMER_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJpc3MiOiJhcnRpZmFjdCIsInVzZXJJZCI6MiwiaWF0IjoxNjczOTgwNDI3fQ.-gHJOIocryVqgTwXpKGMqB6Pb56XOt_wXeK3fFBjv9s"
const WEAPON_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJpc3MiOiJhcnRpZmFjdCIsInVzZXJJZCI6MywiaWF0IjoxNjczOTgwNDYxfQ.WZHLi2NiqK9qGv2ncKJi29oQrmq0uIcSk9rV0XPU4rM"
const CLIENT_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJpc3MiOiJhcnRpZmFjdCIsInVzZXJJZCI6NSwiaWF0IjoxNjczOTgwNDk2fQ.FM5F6_lggx3ciTiCSBUl4c3v2ZguDl_OWwtjZVoJGbw"

export const options = {
    discardResponseBodies: true,
    scenarios: {
      api: {
        executor: 'ramping-vus',
        startVUs: 0,
        stages: [
            { duration: '20s', target: 1000 },
            { duration: '20s', target: 2000 },
            { duration: '20s', target: 5000 },
            { duration: '20s', target: 10000 },
            { duration: '60s', target: 0 },
        ],
        gracefulRampDown: '0s',
      },
    },
  };

export default function() {
    group("/api/artifacts", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/artifacts`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });
        }
    });

    group("/api/users/stalkers", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/users/stalkers`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });
        }
    });

    group("/api/information", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/information`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }
    });

    group("/api/weapon", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/weapon`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }
    });

    group("/api/weapon/{id}", () => {
        let id = 1;

        // Request No. 1
        {
            let url = BASE_URL + `/api/weapon/${id}`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }
    });

    group("/api/orders/{id}", () => {
        let id = 1;

        // Request No. 1
        {
            let url = BASE_URL + `/api/orders/${id}`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });
        }
    });

    group("/api/weapon/available", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/weapon/available`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });
        }
    });

    group("/api/users/current", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/users/current`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }
    });

    group("/api/notifications", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/notifications`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });
        }
    });

    group("/api/orders", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/orders`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }
    });

    group("/api/weapon/requested", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/weapon/requested`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });
        }
    });

    group("/api/users/couriers", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/users/couriers`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });
        }
    });

    group("/api/information/{id}", () => {
        let id = 1;

        // Request No. 1
        {
            let url = BASE_URL + `/api/information/${id}`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }
    });

    group("/api/information/requested", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/information/requested`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });
        }
    });

    group("/api/roles", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/roles`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });
        }
    });

    group("/api/orders/available", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/orders/available`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });
        }
    });

    group("/api/information/available", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/information/available`;
            let params = {headers: {"Authorization": `Bearer ${TOKEN}`}};
            let request = http.get(url, params);

            check(request, {
                "default response": (r) => r.status === 200
            });
        }
    });

}

export function handleSummary(data) {
    return {
      "summary.html": htmlReport(data),
    };
  }